POST  http://localhost/api-qr-tandem/v1/email-soporte.php
Content-Type: "application/json"

{
    "nombre": "Abdel",
    "email": "abdel@gmail.com",
    "asunto": "No es importante",
    "mensaje": "estoy enviando un mensaje a mi mismo" 
}