GET http://localhost/api-qr-tandem/v1/list-users.php
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MTkzOTEyODQsImV4cCI6MTcxOTM5NDg4NCwidXNlcklkIjoxLCJlbWFpbCI6ImNvbmNpbGlvQGdtYWlsLmNvbSJ9.wCD5GP1lM0x8-GVrwLjcfaRpjnDHpOJ394bU7wMkW2s
Content-Type: "application/json"